# Generated by Django 4.1.2 on 2022-10-09 07:42

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Homiylar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fish', models.CharField(max_length=500)),
                ('phono', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('summasi', models.IntegerField()),
                ('sarf_summa', models.IntegerField()),
                ('sana', models.DateTimeField(auto_now_add=True)),
                ('holat', models.CharField(max_length=300)),
            ],
        ),
    ]
