# Generated by Django 4.1.2 on 2022-10-09 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homiy', '0002_homiylar_shaxs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homiylar',
            name='holat',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='homiylar',
            name='sarf_summa',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='homiylar',
            name='summasi',
            field=models.IntegerField(blank=True),
        ),
    ]
