# Generated by Django 4.1.2 on 2022-10-09 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homiy', '0003_alter_homiylar_holat_alter_homiylar_sarf_summa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homiylar',
            name='sarf_summa',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='homiylar',
            name='summasi',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
