# Generated by Django 4.1.2 on 2022-10-09 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homiy', '0004_alter_homiylar_sarf_summa_alter_homiylar_summasi'),
    ]

    operations = [
        migrations.AddField(
            model_name='homiylar',
            name='nomi',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
