# Generated by Django 4.1.2 on 2022-10-12 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homiy', '0006_alter_homiylar_holat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homiylar',
            name='holat',
            field=models.CharField(choices=[('yangi', 'yangi'), ('moderatsiyada', 'moderatsiyada'), ('tasdiqlangan', 'tasdiqlangan'), ('bekor qilingan', 'bekor qilingan')], default='yangi', max_length=20),
        ),
    ]
