# Generated by Django 4.1.2 on 2022-10-12 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homiy', '0008_alter_homiylar_sana'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homiylar',
            name='sana',
            field=models.CharField(default='12.16.2022', max_length=200),
        ),
    ]
