# Generated by Django 4.1.2 on 2022-10-13 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homiy', '0009_alter_homiylar_sana'),
    ]

    operations = [
        migrations.CreateModel(
            name='Talabalar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fish', models.CharField(max_length=500)),
                ('turi', models.CharField(choices=[('bakalavr', 'bakalavr'), ('magister', 'magister')], default='bakalavr', max_length=100)),
                ('otm', models.CharField(max_length=500)),
                ('aj_summa', models.IntegerField()),
                ('contract', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='homiylar',
            name='sana',
            field=models.CharField(default='13.10.2022', max_length=200),
        ),
    ]
