# Generated by Django 4.1.2 on 2022-10-13 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homiy', '0011_alter_talabalar_aj_summa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talabalar',
            name='aj_summa',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
