# Generated by Django 4.1.2 on 2022-10-13 07:23

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('homiy', '0012_alter_talabalar_aj_summa'),
    ]

    operations = [
        migrations.AddField(
            model_name='talabalar',
            name='phono',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None),
        ),
    ]
