# Generated by Django 4.1.2 on 2022-10-13 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homiy', '0014_tolovlar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homiylar',
            name='sarf_summa',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='homiylar',
            name='summasi',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='talabalar',
            name='aj_summa',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
