# Generated by Django 4.1.2 on 2022-10-23 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homiy', '0015_alter_homiylar_sarf_summa_alter_homiylar_summasi_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tolovlar',
            old_name='summa',
            new_name='homiy_summa',
        ),
        migrations.AlterField(
            model_name='homiylar',
            name='phono',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='homiylar',
            name='sana',
            field=models.CharField(default='23.10.2022', max_length=200),
        ),
        migrations.AlterField(
            model_name='talabalar',
            name='phono',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='tolovlar',
            name='sana',
            field=models.CharField(default='23.10.2022', max_length=200),
        ),
    ]
